twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        formato_fecha: 'd/m/Y H:m'
        categoria_repository: '@App\Repository\CategoriaRepository'
